// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEMUf4bo9fwVM1SNydtmLUQNxwG6vSSEY',
    appId: '1:1022485830185:web:bb0eee8bd85ab633dd5a38',
    messagingSenderId: '1022485830185',
    projectId: 'blog-35fb0',
    authDomain: 'blog-35fb0.firebaseapp.com',
    storageBucket: 'blog-35fb0.firebasestorage.app',
    measurementId: 'G-T24C296TF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82wX6y6fZ_W7GUzoD32uL34Mdwl9lVCk',
    appId: '1:1022485830185:android:9b88ecaef16380f8dd5a38',
    messagingSenderId: '1022485830185',
    projectId: 'blog-35fb0',
    storageBucket: 'blog-35fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_4oNk-CVyAfY7Gdj5ScY6h3o5Kf0z3Q',
    appId: '1:1022485830185:ios:5339b6de01754a55dd5a38',
    messagingSenderId: '1022485830185',
    projectId: 'blog-35fb0',
    storageBucket: 'blog-35fb0.firebasestorage.app',
    iosBundleId: 'com.example.ruethive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_4oNk-CVyAfY7Gdj5ScY6h3o5Kf0z3Q',
    appId: '1:1022485830185:ios:5339b6de01754a55dd5a38',
    messagingSenderId: '1022485830185',
    projectId: 'blog-35fb0',
    storageBucket: 'blog-35fb0.firebasestorage.app',
    iosBundleId: 'com.example.ruethive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEMUf4bo9fwVM1SNydtmLUQNxwG6vSSEY',
    appId: '1:1022485830185:web:74905a0c480407c6dd5a38',
    messagingSenderId: '1022485830185',
    projectId: 'blog-35fb0',
    authDomain: 'blog-35fb0.firebaseapp.com',
    storageBucket: 'blog-35fb0.firebasestorage.app',
    measurementId: 'G-402BRZ60TH',
  );
}
